// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj1YDlp-KFRpFH_pwb7xY0ugB94yz6byM',
    appId: '1:16459790914:web:6d0b300db38b1178454bdb',
    messagingSenderId: '16459790914',
    projectId: 'awesome-todo-app-ba35f',
    authDomain: 'awesome-todo-app-ba35f.firebaseapp.com',
    storageBucket: 'awesome-todo-app-ba35f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBisogANHCtcNf7EeV-yQ-nZUCIDof5RnU',
    appId: '1:16459790914:android:c4a7a8f75ba4e0c8454bdb',
    messagingSenderId: '16459790914',
    projectId: 'awesome-todo-app-ba35f',
    storageBucket: 'awesome-todo-app-ba35f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqcOkoRI301Rvby3MGdxdTyD0CzcOO_UM',
    appId: '1:16459790914:ios:35bfb394030e6173454bdb',
    messagingSenderId: '16459790914',
    projectId: 'awesome-todo-app-ba35f',
    storageBucket: 'awesome-todo-app-ba35f.firebasestorage.app',
    iosBundleId: 'com.evershare.fluttermasrtering.flutterMastering',
  );
}
